Imports System.Collections.Generic
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace T198803

    Partial Public Class Appointment
        Public Property UniqueId() As Integer
        Public Property Type() As Integer?
        Public Property StartDate() As Date?
        Public Property EndDate() As Date?
        Public Property AllDay() As Boolean?
        Public Property Subject() As String
        Public Property Location() As String
        Public Property Description() As String
        Public Property Status() As Integer?
        Public Property Label() As Integer?
        Public Property ResourceId() As Integer?
        Public Property ResourceIds() As String
        Public Property ReminderInfo() As String
        Public Property RecurrenceInfo() As String
        Public Property PercentComplete() As Integer?
        Public Property CustomField1() As String
    End Class
End Namespace
