Imports System.Collections.Generic
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace T198803

    Partial Public Class Resource
        Public Property Id() As Integer
        Public Property IdSort() As Integer?
        Public Property ParentId() As Integer?
        Public Property Description() As String
        Public Property Color() As Integer?
        Public Property Image() As Byte()
        Public Property CustomField1() As String
    End Class
End Namespace
